/**
 * OTC Synthetic Candle Generator
 *
 * Uses Geometric Brownian Motion (GBM) with a per-asset deterministic seed so
 * candles look like real forex data, run 24/7, and are fully server-controlled
 * (enables manipulation).
 *
 * Formula (per tick):
 *   S(t+dt) = S(t) * exp((mu - sigma^2/2) * dt + sigma * sqrt(dt) * Z)
 *   where Z ~ N(0, 1)
 *
 * Candles are deterministic given (asset, tfSeconds, candleEpoch) — meaning
 * every client will see the same OHLC for the same minute. Only the *current*
 * (still-forming) candle is affected by manipulation drift before emission.
 */

export type OtcCandle = {
  time:  number; // epoch seconds (bar open time)
  open:  number;
  high:  number;
  low:   number;
  close: number;
};

export type AssetParams = {
  seed:    number;  // deterministic random seed
  base:    number;  // reference price (seed value)
  vol:     number;  // annualized volatility (e.g. 0.07 = 7%)
  decimals: number; // price decimals for formatting
};

// ── 21 OTC assets ───────────────────────────────────────────────────────
export const OTC_ASSETS: Record<string, AssetParams> = {
  AUDCAD: { seed: 11, base: 0.910, vol: 0.055, decimals: 5 },
  AUDCHF: { seed: 12, base: 0.580, vol: 0.060, decimals: 5 },
  AUDJPY: { seed: 13, base: 96.30, vol: 0.080, decimals: 3 },
  AUDNZD: { seed: 14, base: 1.090, vol: 0.045, decimals: 5 },
  CADCHF: { seed: 15, base: 0.655, vol: 0.055, decimals: 5 },
  EURAUD: { seed: 16, base: 1.690, vol: 0.060, decimals: 5 },
  EURCHF: { seed: 17, base: 0.969, vol: 0.050, decimals: 5 },
  EURGBP: { seed: 18, base: 0.855, vol: 0.050, decimals: 5 },
  EURJPY: { seed: 19, base: 162.5, vol: 0.080, decimals: 3 },
  EURUSD: { seed: 20, base: 1.085, vol: 0.070, decimals: 5 },
  GBPCHF: { seed: 21, base: 1.130, vol: 0.065, decimals: 5 },
  GBPJPY: { seed: 22, base: 190.1, vol: 0.090, decimals: 3 },
  GBPNZD: { seed: 23, base: 2.170, vol: 0.070, decimals: 5 },
  GBPUSD: { seed: 24, base: 1.268, vol: 0.070, decimals: 5 },
  NZDCAD: { seed: 25, base: 0.805, vol: 0.055, decimals: 5 },
  NZDCHF: { seed: 26, base: 0.530, vol: 0.060, decimals: 5 },
  NZDJPY: { seed: 27, base: 90.50, vol: 0.080, decimals: 3 },
  NZDUSD: { seed: 28, base: 0.592, vol: 0.070, decimals: 5 },
  USDCAD: { seed: 29, base: 1.362, vol: 0.060, decimals: 5 },
  USDCHF: { seed: 30, base: 0.893, vol: 0.060, decimals: 5 },
  USDJPY: { seed: 31, base: 149.8, vol: 0.080, decimals: 3 },
};

export function isOtcAsset(symbol: string): boolean {
  const base = symbol.replace("-OTC", "");
  return base in OTC_ASSETS;
}

export function getOtcParams(symbol: string): AssetParams | null {
  const base = symbol.replace("-OTC", "");
  return OTC_ASSETS[base] ?? null;
}

// ── Deterministic PRNG (Mulberry32) ─────────────────────────────────────
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Box-Muller: uniform [0,1) → standard normal
function randn(rand: () => number): number {
  let u = 0, v = 0;
  while (u === 0) u = rand();
  while (v === 0) v = rand();
  return Math.sqrt(-2.0 * Math.log(u)) * Math.cos(2.0 * Math.PI * v);
}

// ── Core: compute OHLC for a single candle deterministically ────────────
/**
 * Given asset params and the epoch of a candle, returns the open/high/low/close.
 * Each candle is generated by walking from its deterministic "open" through N
 * sub-ticks using GBM. Same (asset, epoch) → same OHLC across all clients.
 */
function candleForEpoch(
  params: AssetParams,
  tfSec: number,
  epoch: number,
): OtcCandle {
  // Seed: asset + absolute candle index (so neighbor candles connect)
  const candleIdx = Math.floor(epoch / tfSec);
  const rand = mulberry32(params.seed * 1_000_003 + candleIdx);

  // Open = close of the previous candle (walk deterministically from "time zero")
  // For efficiency we compute open using a per-candle anchor drift + seed base
  // that slowly drifts over days — keeping price in a realistic band.
  const prevIdx = candleIdx - 1;
  const prevRand = mulberry32(params.seed * 1_000_003 + prevIdx);
  // Walk anchors: deterministic low-frequency drift (daily cycles)
  const dayCycle = Math.sin(candleIdx / 1440) * 0.003; // ±0.3% slow drift
  const openAnchor = params.base * (1 + dayCycle);

  // Apply small random continuity offset from the previous candle
  const prevNoise = (prevRand() - 0.5) * params.base * 0.0005;
  const open = +(openAnchor + prevNoise).toFixed(params.decimals + 2);

  // Sub-ticks inside this candle (e.g. 60 ticks per M1 = 1 per second)
  const subTicks = Math.max(10, Math.min(60, tfSec));
  const dt = 1 / (252 * 24 * 60 * 60 / tfSec) / subTicks; // annualized
  const sigma = params.vol;
  const mu = 0;

  let s = open;
  let high = open, low = open;
  for (let i = 0; i < subTicks; i++) {
    const z = randn(rand);
    s = s * Math.exp((mu - sigma * sigma / 2) * dt + sigma * Math.sqrt(dt) * z);
    if (s > high) high = s;
    if (s < low)  low  = s;
  }
  const close = +s.toFixed(params.decimals + 2);
  high = +high.toFixed(params.decimals + 2);
  low  = +low.toFixed(params.decimals + 2);

  return { time: candleIdx * tfSec, open, high, low, close };
}

// ── Public API ──────────────────────────────────────────────────────────

/** Returns the last `count` closed candles for the given asset+timeframe. */
export function getHistoricalCandles(
  symbol: string,
  tfSec: number,
  count: number,
  nowSec: number = Math.floor(Date.now() / 1000),
): OtcCandle[] {
  const params = getOtcParams(symbol);
  if (!params) return [];
  const currentIdx = Math.floor(nowSec / tfSec);
  const candles: OtcCandle[] = [];
  for (let i = count; i >= 1; i--) {
    const epoch = (currentIdx - i) * tfSec;
    candles.push(candleForEpoch(params, tfSec, epoch));
  }
  return candles;
}

/** Returns the current (still-forming) candle, with `close` based on how far
 *  through the candle we are. */
export function getCurrentCandle(
  symbol: string,
  tfSec: number,
  nowSec: number = Math.floor(Date.now() / 1000),
): OtcCandle | null {
  const params = getOtcParams(symbol);
  if (!params) return null;
  const currentIdx = Math.floor(nowSec / tfSec);
  // Use a "next-candle" seed so the forming candle extrapolates smoothly
  const candle = candleForEpoch(params, tfSec, currentIdx * tfSec);
  // Progress within candle (0..1)
  const progress = (nowSec - candle.time) / tfSec;
  // Interpolate close: linear between open and the "target" close
  const interpolatedClose = candle.open + (candle.close - candle.open) * Math.min(1, Math.max(0, progress));
  const currentHigh = Math.max(candle.open, interpolatedClose, candle.high * Math.min(1, progress + 0.2));
  const currentLow  = Math.min(candle.open, interpolatedClose, candle.low  * Math.max(0.0001, 1 - (1 - progress) * 0.2));
  return {
    time: candle.time,
    open: candle.open,
    high: +currentHigh.toFixed(params.decimals + 2),
    low:  +currentLow.toFixed(params.decimals + 2),
    close: +interpolatedClose.toFixed(params.decimals + 2),
  };
}

/** Returns the current price (close of the forming candle), after manipulation. */
export function getCurrentPrice(
  symbol: string,
  tfSec: number = 60,
  nowSec: number = Math.floor(Date.now() / 1000),
): number {
  const c = getCurrentCandle(symbol, tfSec, nowSec);
  return c?.close ?? 0;
}
